config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/home'

  resources :confirmations, only:[:index]

  resources :appartments do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]
  resources :conversations, only: [:create, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :user

end

app/models/appartment.rb
class Appartment < ApplicationRecord
  belongs_to :user
  has_attachment :photo
  has_attachments :pictures
  has_many :reviews
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
require 'date'

class Booking < ApplicationRecord
  belongs_to :appartment
  belongs_to :user
  after_create :send_confirmation

  def length_of_stay
    booking_start = self.start_date.to_date
    booking_end = self.end_date.to_date
    (booking_end - booking_start).to_i
  end

  def total_price
    length_of_stay * self.appartment.price
  end

  def send_confirmation
    @confirmation = Confirmation.create(booking_id: self.id, text: self.text_message)
    @confirmation.save
  end


end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :booking

 # before_create do
  #  @conversation = Conversation.find(params[:conversation_id])
  #  if @conversation.nil?
  #    return Conversation.create
  #  end
  #end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  #belongs_to :user, class_name: "User", foreign_key: "user_id"
  #belongs_to :appartment, class_name: "User", foreign_key: "appartment_id"
  #validates_uniqueness_of :user_id, scope: :appartment_id

  #scope :between, -> (user_id, appartment_id) { where("conversations.user_id = ? AND conversations.appartment_id = ? ) OR (conversations.appartment_id = ? AND conversations.user_id = ?", user_id, appartment_id, appartment_id, user_id)}
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :appartment

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :avatar
  has_many :reviews
  has_many :bookings
  has_many :users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]



    def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = current_user
    @bookings = Booking.all
  end

  def new
    find
    @booking = Booking.new
  end

  def create
    find
    @booking = Booking.create(booking_params)
    @booking.user_id = @user.id
    @booking.appartment_id = @appartment.id
    @booking.save
    redirect_to appartments_path(@appartment)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(params(:status))
  end

  private
  def booking_params
    params.require(:booking).permit(:text_message, :start_date, :end_date)
  end

  def find
    @user = current_user
    @appartment = Appartment.find(params[:appartment_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    find
    @review = Review.new
    @review.user_id = @user.id
    @review.appartment_id = @appartment.id
  end

  def create
    find
    @review = Review.create(review_params)
    @review.user_id = @user.id
    @review.appartment_id = @appartment.id
    @review.save
    redirect_to appartment_path(@appartment)
  end

  private

  def review_params
    params.require(:review).permit(:testimonial, :rating)
  end

  def find
    @user = current_user
    @appartment = Appartment.find(params[:appartment_id])

  end

end

app/helpers/appartments_helper.rb
module AppartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkiAway</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= favicon_link_tag 'logo.png' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body>
  <%= render 'shared/navbar' %>

  <%= yield %>
  <%= render 'shared/footer' %>


    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag "application" %>
  <%= cloudinary_js_config %>

  <%= yield(:after_js) %>


</body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<!-- Discover -->
<section id="discover">
  <div class="container">
    <div class="col-m-4">
      <h2 class="section-heading">Discover</h2>
      <h4 class="section-sub-header">Discover our offering...</h4>
    </div>
  </div>
  <div class="card-wrapper">
    <% @appartments = Appartment.all %>
    <% @appartments.sample(3).each do |appartment| %>
    <div class="card">

      <div class="card-image" style="background-image: url('<%= appartment.photo? ? cl_image_path(appartment.photo.path) : '/assets/winter_shack.jpeg' %>')"
      ></div>
      <div class="card-content">
        <div class="appartment-type-header"><%= appartment.appartment_type %></div>
        <div class="description-header"><%= link_to appartment.header, appartment_path(appartment)%></div>
        <div class="price-header">From <%= appartment.price %> € per night</div>
        <div class="card-icons">
          <% appartment.reviews.average(:rating).to_i.times do %>
          <i class="fa fa-snowflake-o" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>


<!-- Testimonials -->
<section id="testimonials">
  <div class="container">
    <div class="col-m-4">
      <h2 class="section-heading">Testimonials</h2>
      <h4 class="section-sub-header">See what others say...</h4>
    </div>
  </div>
  <div class="card-wrapper">
    <% @reviews = Review.all %>
    <% @reviews.sample(3).each do |review| %>
    <div class="card">
      <div class="card-head sm-review-card-head">
        <div id="lg-rating">
          <% review.rating.times do %>
          <i class="fa fa-snowflake-o" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="review-user center-items"><% avatar_url = review.user.facebook_picture_url || (review.user.avatar? ? cl_image_path( review.user.avatar.path, :crop => "fill") : "https://kitt.lewagon.com/placeholder/users/ssaunier") %>
          <%= image_tag avatar_url, class: "sm-avatar"%>
          <p> <%= review.user.first_name %> <%= review.user.last_name %></p>
        </div>
      </div>
      <div class="card-body center-items" id="testimonial-link">
        <p>" <%= link_to review.testimonial, appartment_path(review.appartment_id)%> "</p>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>
</section>

<!-- How it works -->
<section id="skiaway">
  <div class="container">
    <div class="row"></div>
    <div class="col-m-4">
      <h2 class="section-heading">How it works</h2>
      <h4 class="section-sub-header">Easy, quick, perfect...</h4>
      <div class="card-wrapper">
        <div class="row">
          <i class="fa fa-calendar center-items" aria-hidden="true" style="color: #B7989B; font-size: 7em"></i>
          <h5 class="center-items">Holidays?</h5>
        </div>
        <div class="row">
          <i class="fa fa-search center-items" aria-hidden="true" style="color: #B7989B; font-size: 7em"></i>
          <h5>Find your perfect house, </h5>
          <h5>wherever you want to go...</h5>
        </div>
        <div class="row">
          <i class="fa fa-home center-items" aria-hidden="true" style="color: #B7989B; font-size: 7em"></i>
          <h5>Enjoy your skiing holidays,</h5>
          <h5>at a place like home</h5>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Enjoy Your Holidays,</h1>
    <h1>feeling like home</h1>
  </div>
</div>

app/views/shared/_card.html.erb
  <% @appartments.each do |appartment| %>
  <div class="col-sm-4">
    <div class="card">
     <div class="card-image" style="background-image: url('<%= appartment.photo? ? cl_image_path(appartment.photo.path) : '/assets/winter_shack.jpeg' %>')"></div>
     <div class="card-content">
      <div class="appartment-type-header"><%= appartment.appartment_type %></div>
      <div class="description-header"><%= link_to appartment.header, appartment_path(appartment)%></div>
      <div class="price-header">From <%= appartment.price %> € per night</div>
      <div class="card-icons">
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-section">
    <div class="footer-imprint"><p>© SkiAway, Inc.</p></div></div>

<!--About-->
  <div class="footer-section">
    <div class="footer-links">
      <div class="footer-header"><p>About</p></div>
      <a href=""><p>Contact</p></a>
      <a href=""><p>Careers</p></a>
      <a href=""><p>FAQ</p></a>
    </div>
  </div>

  <!--Travelling-->
    <div class="footer-section">
    <div class="footer-links">
      <div class="footer-header"><p>Travelling</p></div>
      <a href=""><p>Why SkiAway</p></a>
      <a href=""><p>Trust & Safety</p></a>
      <a href=""><p>FAQ</p></a>
    </div>
  </div>

  <!--Hosting-->
    <div class="footer-section">
    <div class="footer-links">
      <div class="footer-header"><p>Hosting</p></div>
      <a href=""><p>Why Host</p></a>
      <a href=""><p>Hospitality</p></a>
      <a href=""><p>FAQ</p></a>
    </div>
  </div>

  <!--Icons-->
  <div class="footer-section">
    <div class="footer-icons">
      <div class="icons-wrapper">
      <a href="#"><i class="fa fa-instagram"></i></a>
      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_large_review_card.html.erb
<div class="large-review-card-container">
  <% @appartment.reviews.each do |r| %>
  <div class="large-review-card">
    <div class="card-head">
      <div id="lg-rating">
        <% r.rating.times do %>
        <i class="fa fa-snowflake-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="review-user center-items"><% avatar_url = r.user.facebook_picture_url || (r.user.avatar? ? cl_image_path( r.user.avatar.path, :crop => "fill") : "https://kitt.lewagon.com/placeholder/users/ssaunier") %>
        <%= image_tag avatar_url, class: "lg-avatar"%>
        <p> <%= r.user.first_name %> <%= r.user.last_name %></p>
      </div>
    </div>
    <div class="card-body"><p>"<%= r.testimonial %>"</p></div>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
  <%= image_tag "logo.png", id: "logo" %>
  </a>



  <!-- Right Navigation -->
   <% if user_signed_in? %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="/appartments/new" class="navbar-wagon-item navbar-wagon-link">Host </a>
    <a href="/bookings" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="/confirmations" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || (current_user.avatar? ? cl_image_path( current_user.avatar.path, :crop => "fill") : "https://kitt.lewagon.com/placeholder/users/ssaunier") %>
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        <%= image_tag avatar_url, class: "avatar driodiwb.toggle", id: "navbar-wagon-menu" %></a>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile",  edit_user_registration_path  %></li>
          <li><a href="#">Dashboard</a></li>
          <li><%= link_to t(".sign_out", default: "Logout"), destroy_user_session_path, method: :delete%></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Host", new_appartment_path %></li>
        <li><a href="/appartments/new">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
  <% else %>
  <div class="user-not-signed-in">
  <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  %>
  <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link"  %>
  </div>
  <% end %>
</div>