config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/home'

  resources :confirmations, only:[:index]

  resources :appartments do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]
  resources :conversations, only: [:create, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :user

end

app/models/appartment.rb
class Appartment < ApplicationRecord
  belongs_to :user
  has_attachment :photo
  has_attachments :pictures
  has_many :reviews
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
require 'date'

class Booking < ApplicationRecord
  belongs_to :appartment
  belongs_to :user
  after_create :send_confirmation

  def length_of_stay
    booking_start = self.start_date.to_date
    booking_end = self.end_date.to_date
    (booking_end - booking_start).to_i
  end

  def total_price
    length_of_stay * self.appartment.price
  end

  def send_confirmation
    @confirmation = Confirmation.create(booking_id: self.id, text: self.text_message)
    @confirmation.save
  end


end

app/models/confirmation.rb
class Confirmation < ApplicationRecord
  belongs_to :booking

 # before_create do
  #  @conversation = Conversation.find(params[:conversation_id])
  #  if @conversation.nil?
  #    return Conversation.create
  #  end
  #end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  #belongs_to :user, class_name: "User", foreign_key: "user_id"
  #belongs_to :appartment, class_name: "User", foreign_key: "appartment_id"
  #validates_uniqueness_of :user_id, scope: :appartment_id

  #scope :between, -> (user_id, appartment_id) { where("conversations.user_id = ? AND conversations.appartment_id = ? ) OR (conversations.appartment_id = ? AND conversations.user_id = ?", user_id, appartment_id, appartment_id, user_id)}
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :appartment

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :avatar
  has_many :reviews
  has_many :bookings
  has_many :users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]



    def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/appartments_controller.rb
class AppartmentsController < ApplicationController

  def index
    @appartments = Appartment.all
    #@appartments_address = Appartment.where.not(latitude: nil, longitude: nil)

    #@markers = Gmaps4rails.build_markers(@appartments_address) do |appartment, marker|
    #  marker.lat appartment.latitude
    #  marker.lng appartment.longitude
    #   marker.infowindow render_to_string(partial: "/appartments/map_box", locals: { appartment: appartment })
    #end
  end

  def new
    @appartment = Appartment.new
  end

  def create
    @user = current_user
    @appartment = Appartment.new(appartment_params)
    @appartment.user_id = @user.id
    @appartment.save
    redirect_to pages_home_path
  end

  def show
    @appartment = Appartment.find(params[:id])
  end

  def edit
    @appartment = Appartment.find(params[:id])
  end

  def update
    @appartment = Appartment.find(params[:id])
    @appartment.update(appartment_params)
  end

  private

  def appartment_params
    params.require(:appartment).permit(:address, :description, :header, :appartment_type, :price, :photo, pictures: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, exept: :home
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,        keys: [:first_name, :last_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = current_user
    @bookings = Booking.all
  end

  def new
    find
    @booking = Booking.new
  end

  def create
    find
    @booking = Booking.create(booking_params)
    @booking.user_id = @user.id
    @booking.appartment_id = @appartment.id
    @booking.save
    redirect_to appartments_path(@appartment)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(params(:status))
  end

  private
  def booking_params
    params.require(:booking).permit(:text_message, :start_date, :end_date)
  end

  def find
    @user = current_user
    @appartment = Appartment.find(params[:appartment_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    find
    @review = Review.new
    @review.user_id = @user.id
    @review.appartment_id = @appartment.id
  end

  def create
    find
    @review = Review.create(review_params)
    @review.user_id = @user.id
    @review.appartment_id = @appartment.id
    @review.save
    redirect_to appartment_path(@appartment)
  end

  private

  def review_params
    params.require(:review).permit(:testimonial, :rating)
  end

  def find
    @user = current_user
    @appartment = Appartment.find(params[:appartment_id])

  end

end

app/helpers/appartments_helper.rb
module AppartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/appartments/index.html.erb
<section>
        <%= render 'shared/card' %>
        <div id="map" style="width: 100%; height: 350px;"></div>
</section>

<!--
<% content_for(:after_js) do %>
<script>
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
</script>
<% end %>
-->

app/views/appartments/new.html.erb
<div class="bg" style="background-image: linear-gradient(rgba(255,255,255,0.6),rgba(255,255,255,0.6)), url('/assets/winter_wonderland.jpeg' );">
  <div class="container" >
    <section id="new-appartment">
      <h1>New appartment</h1>
    </section>
    <section>
      <div class="form-description">
        <%= simple_form_for [@appartment] do |f| %>
        <div class="row">
          <div class="col-sm-6 flex-space-between" >
            <%= f.input :photo, label: "Main picture", as: :attachinary %>
            <%= f.input :pictures, label: "More pictures of appartment", as: :attachinary %>
          </div>
        </div>
        <%= f.input :address, placeholder: "e.g. Unterer Mooserweg 2, 6580 Sankt Anton am Arlberg" %>
        <%= f.input :header, placeholder: "e.g. Cosy appartment in Swiss Alps" %>

        <%= f.input :appartment_type, collection: ["Entire house", "Entire appartment", "Room"] %>

        <%= f.input :wlan, :as => :boolean, :label => false, :inline_label => true, label: "WLAN" %>
        <%= f.input :bathtube, :as => :boolean, :label => false, :inline_label => true, label: "Bathtube" %>

        <%= f.input :bed, collection: (1..15) %>
        <%= f.input :description, as: :text, placeholder: "min. 200 characters", input_html: {cols: 5, rows: 7} %>
        <%= f.input :price, placeholder: " in EUR and per night" %>
        <%= f.submit "Create new appartment", class: "btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/appartments/show.html.erb
 <!--Main picture-->
 <div class="container">
   <section class="section-wrapper">
    <div class="picture" id="picture-wrapper">
      <% if @appartment.photo.nil? %>
      <%= image_tag '/assets/winter_shack.jpeg' %>
      <% else %>
      <%= cl_image_tag @appartment.photo.path, class: "picture" %>
      <% end %>
    </div>
  </section>

  <!-- Picture collection-->
  <section class="section-wrapper">
    <div class="section-sub-header">See more</div>
    <div class="small-pictures-wrapper">
      <% if @appartment.pictures.empty? %>
      <% 10.times do %>
      <%=  image_tag '/assets/winter_shack.jpeg', class: "small-picture" %>
      <% end %>
      <% else %>
      <% @appartment.pictures.each do |picture| %>
      <%= cl_image_tag picture.path, class: "small-picture" %>
      <% end %>
      <% end %>
    </div>
  </section>

  <!--Short header-->
  <section class="section-wrapper">
    <h2 class="section-heading">
      <%= @appartment.header %> <%@appartment.reviews.average(:rating).to_i.times do %>
      <i class="fa fa-snowflake-o" aria-hidden="true"></i>
      <% end %>
    </h2>
  </section>

  <!--Description-->
  <section class="section-wrapper">
    <h4 class="section-sub-header">Description</h4>
    <div class="section-borders">
      <p><%= @appartment.description %></p>
    </div>
  </section>


  <!--Details-->
  <section class="section-wrapper">
    <h4 class="section-sub-header">Details</h4>
    <div class="section-borders">
      <div class="description-icons">
        <p>Type : <%= @appartment.appartment_type %></p>
        <div class="bed-icon">
          <% @appartment.bed.times do %>
          <i class="fa fa-bed" aria-hidden="true"></i>
          <% end %>
        </div>
        <i class="fa fa-wifi" aria-hidden="true"> :
          <% if @appartment.wlan == true  %>
          <%= 'Yes'%>
            <% else %>
            <%='No'%>
            <% end %>
          </i>
        <i class="fa fa-bath" aria-hidden="true"> :
          <% if @appartment.bathtube == true  %>
          <%= 'Yes'%>
            <% else %>
            <%= 'No'%>
            <% end %></i>
      </div>
    </section>

    <!--Address-->
    <section class="section-wrapper">
      <h4 class="section-sub-header">Address</h4>
      <div class="section-borders">
        <div id="address-section">
          <p><%= @appartment.address %></p>
          <div class="map">
          </div>
        </div>
      </div>
    </section>

    <!--Reviews-->
    <section class="section-wrapper">
      <h4 class="section-sub-header">Reviews</h4>
      <div class="section-borders">
        <%= render 'shared/large_review_card' %>
        <%= link_to "Add review", new_appartment_review_path(@appartment), class: "btn btn-primary" %>
      </div>
    </section>
  </div>

  <!--Booking-->
 <div class="booking-link flex-space-between">
  <div class="price-info">
    <h5><%= @appartment.price %>€ per night</h5>
  </div>
  <div class="booking-button">
  <%= link_to "Book", new_appartment_booking_path(@appartment), class: "btn btn-primary" %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <section>
    <div class="section-wrapper">
      <div class="section-heading">
        <h2>Bookings</h2>
        <div class="section-sub-header">
          <h4>See all your Bookings</h4>
        </div>
      </div>
      <div class="large-review-card-container">
        <% @bookings.each do |b| %>
        <% if b.user_id == current_user.id %>
        <div class="large-review-card">
          <div class="card-head">
            <p><%= (b.start_date).strftime("%m/%d/%Y")  %> - <%=(b.end_date).strftime("%m/%d/%Y") %></p>
            <% if b.status == 'accepted' %>
            <div class="accepted"><%= b.status %></div>
            <% elsif b.status == 'declined' %>
            <div class="declined"><%= b.status %></div>
            <% else %>
            <div class="pending"><%= b.status %></div>
            <% end %>

          </div>
          <div class="booking-card-content">
            <div class="column-flex-start">
              <% photo_url = b.appartment.photo? ? b.appartment.photo.path : '/assets/winter_shack.jpeg' %>
              <%= cl_image_tag photo_url, height: 80, width: 80, crop: :fill  %>
              <p> <strong>Address:</strong> <%= b.appartment.address %></p>
              <p><strong>Total Price:</strong> <%= b.total_price %>€</p>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <section>
    <div class="section-wrapper">
      <div class="form-description">
        <%= simple_form_for [@appartment, @booking] do |f|%>
        <%= f.input :start_date, input_html: {class: "datepicker"}, placeholder: "Arrival", as: :string %>
        <%= f.input :end_date, input_html: {class: "datepicker"}, placeholder: "Departure", as: :string %>
        <%= f.input :text_message, as: :text, input_html: {cols: 5, rows: 10} %>
        <%= f.submit "Book", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </section>
</div>